site_name: Ilyass Khaleq Mansourui
theme:
  name: "ivory"



extra_css:
  - css/extra.css



nav:
  - Introducci√≥n: introduccio.md
  - Ubuntu:
      - Sprint 2: sprint2.md
      - Sprint 3: sprint3.md